<<<<<<< HEAD
# Generated by Django 4.2 on 2023-06-28 13:49
=======
# Generated by Django 4.1.1 on 2023-07-05 13:08
>>>>>>> f801d437f1cc95887d86d3dcb3b12409866d48a3

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
<<<<<<< HEAD
        migrations.AlterModelTable(
            name="user",
            table="User",
        ),
=======
        migrations.AlterModelTable(name="user", table="User",),
>>>>>>> f801d437f1cc95887d86d3dcb3b12409866d48a3
    ]
