# Generated by Django 4.1.1 on 2023-07-05 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enroll", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(name="user", table="User",),
    ]
