# Generated by Django 4.1 on 2022-08-28 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="products", name="price",),
    ]
