# Generated by Django 4.1.1 on 2022-09-08 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_dummy"),
    ]

    operations = [
        migrations.RenameModel(old_name="Products", new_name="Prod",),
    ]
