# Generated by Django 4.1 on 2022-08-28 00:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_remove_products_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dummy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=255)),
                (
                    "kgrams",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255), size=None
                    ),
                ),
                ("cs", models.DecimalField(decimal_places=0, max_digits=225)),
                (
                    "hashlist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.DecimalField(
                            decimal_places=0, max_digits=225
                        ),
                        size=None,
                    ),
                ),
            ],
            options={"db_table": "Dummy",},
        ),
    ]
