# Generated by Django 4.1.1 on 2022-09-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_items_delete_prod"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="desc",
            field=models.TextField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="items",
            name="price",
            field=models.DecimalField(decimal_places=2, default=9.99, max_digits=15),
        ),
        migrations.AddField(
            model_name="items",
            name="title",
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
