# Generated by Django 4.1 on 2022-08-28 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_delete_dummy"),
    ]

    operations = [
        migrations.DeleteModel(name="Products",),
    ]
