# Generated by Django 4.1.1 on 2022-11-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0005_items_desc_items_price_items_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items", name="desc", field=models.TextField(default=None),
        ),
        migrations.AlterField(
            model_name="items",
            name="title",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
