# Generated by Django 4.1.1 on 2022-11-02 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_alter_items_desc_alter_items_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="items",
            name="desc",
            field=models.TextField(blank=True, null=True),
        ),
    ]
