# Generated by Django 4.1 on 2022-08-28 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_rename_products_product"),
    ]

    operations = [
        migrations.RenameModel(old_name="Product", new_name="Products",),
    ]
