# Generated by Django 4.2 on 2023-07-20 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BlackListedTokens",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.TextField()),
                ("expired_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "BlackListedTokens",
            },
        ),
    ]
