# Generated by Django 5.2.13 on 2026-05-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_no",
            field=models.CharField(default="", max_length=20),
        ),
    ]
