# Generated by Django 4.2 on 2023-06-11 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("modelForms13", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="user_registration",
        ),
    ]
