FROM python:3.9.12


WORKDIR /app 

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY . .

# To make application available externally, we need to put 0.0.0.0:8000 in CMD
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]